version: 2

models:
  - name: dim_store_norm
    description: "Dimension table for store."
    columns:
      - name: store_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: county_number
        description: "The foreign key to the country dimension table"
        tests:
          - relationships:
              to: ref('dim_county')
              field: county_number
  - name: dim_county
    description: "Dimension table for county."
    columns:
      - name: county_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_item_norm
    description: "Dimension table for item."
    columns:
      - name: item_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: category
        description: "The foreign key to the category dimension table"
        tests:
          - relationships:
              to: ref('dim_category')
              field: category
      - name: vendor_number
        description: "The foreign key to the vendor dimension table"
        tests:
          - relationships:
              to: ref('dim_vendor')
              field: vendor_number
  - name: dim_category
    description: "Dimension table for category."
    columns:
      - name: category
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: dim_vendor
    description: "Dimension table for vendor."
    columns:
      - name: vendor_number
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
